# Generated by Django 5.1.1 on 2024-09-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('loanid', models.IntegerField(primary_key=True, serialize=False)),
                ('creditscore', models.IntegerField()),
                ('age', models.IntegerField()),
                ('account_no', models.IntegerField()),
                ('loan_purpose', models.IntegerField()),
            ],
        ),
    ]
